### ISSUE TITLE
Pages returns Error 324 (net::ERR_EMPTY_RESPONSE)

### ISSUE THREAD

**Issue by CHEF-KOCH** [opengapps/opengapps#297]
If I want to visit the page it returns ERR_EMPTY_RESPONSE on Chromium, but Ping works just fine. 

This is now since several days.

What have I tried?
* Reset Windows Winsock, disabled unbound/dnscrypt and use Windows own DNS mechanism [still the same]
* Ping works (both behind DNscrypt/unbound and Win. DNS) not any loss 
* Tried stable Chrome/Chromium version .. same
* Tried with and without addons, same. First I was thinking because uMatrix but no luck. 
* Tried to fully uninstall AdGuard (currently testing it) and it's SSL feature (also ensured the certificate is removed from certmgr.msc)
* Tried to reboot (just for the lulz), to see if Win 10 Ent. LTSB N x64 is may the issue. But still the same.
* Latest patched system and this is the only page I ever seen with that error. All other pages working fine. 
* Tried opengapps.org with and without www prefix. 
* Tried Firefox and Tor Browser (FF the same issue but Tor works).
* Tried to change default DNS server within router, Google/OpenDNS.

**Comment by bgiesing** [comment]
@CHEF-KOCH This is most likely an issue with your computer/Chrome not us.

Some causes include:
1. There is a problem with your ISP internet connection.
2. Google Chrome specific issue usually resolved by just clearing your cache or disabling Extensions.
3. Faulty Router or a Router misconfiguration.
4. Spyware, adware or malware installed on your computer or in your Browser.
5. Corrupt or invalid Registry keys on your computer.
6. Corrupt cache in your computer's Temporary Internet folder that requires manual deletion by going to the Temp folder and deleting that cache.

**Comment by CHEF-KOCH** [comment]
I can't tell how useless this is, I mean I'm able to google myself. I expected some advise to debug this, I in meantime tried 3 other Chromium versions, still the same. If I connect via Tor it works, my provider itself not blogs that page because otherwise I could't in general not connect to GitHub. 

Something has changed in Chromium or the page itself, as reported it worked well until ... I don't know.

**Comment by bgiesing** [comment]
You just answered your own question:

> If I connect via Tor it works, my provider itself not blogs that page
because otherwise I could't in general not connect to GitHub.

It's your ISP and/or browser not us.

**Comment by CHEF-KOCH** [comment]
It not explained why it worked before ... ?

**Comment by bgiesing** [comment]
@CHEF-KOCH well if it's because your ISP (which seems likely because the Tor comment), they are blocking GitHubs servers which Tor circumvents so the only option would be switch internet companies.

**Comment by USBhost** [comment]
@bgiesing Wouldn't a web proxy work to?
If the ISP blocked github Wouldn't ping also not work?

**Comment by CHEF-KOCH** [comment]
I guess it's GitHub issue then according to [this](https://stackoverflow.com/questions/13176706/error-324-neterr-empty-response-error-in-joomla-3-0-php-with-parentdisplay), a lot of people reporting similar things, because server side config. Maybe author of opengapps.org could ask GitHub to fix this. Or I contact GitHub now, because if ping works why the page should't work, my ISP also not blocks GitHub or any of it's pages I'm 100% sure. Because in my entire internet area I never found any blocked page (by ISP directly).

**Comment by mfonville** [comment]
Can you try with Google's DNS servers set?
Are you sure you browse to OpenGApps.org without www. in front?

**Comment by CHEF-KOCH** [comment]
Updated OP, will try to set Google DNS in router now.

**Comment by mfonville** [comment]
Many years ago I had a similar issue when my router's MTU was faulty. So I Googled the error with MTU added; and it would explain why it works via a tor tunnel.  Could you use the hints from http://www.techtubby.com/how-to-fix-error-324-neterr_empty_response-the-server-closed-the-connection/ ?

**Comment by CHEF-KOCH** [comment]
Well guys you're all awesome but after around 3 hours of debugging and different configs and all such possibility's I found out it's Chromium issue, but not to the mentioned reasons. It's just something internal because I tried it with Android + Firefox and it works there, also with Android Chrome and Chromium (dev) version (I used the F-Droid app to download Chromium dev version on Android)

@mfonville 
Thanks I will try, can you do me a favor or someone other to test my linked Chromium version to check against? If we get the same problem then something really needs to be fixed in Chromium because then it not only affects me. 

Sr, for all the troubles. If someone can verify/confirm I close this and link into Chromium Project to fix this.

**Comment by mfonville** [comment]
@CHEF-KOCH 
I have no Windows installation at home, so I can't test for you. I believe @bgiesing has.

**Comment by bgiesing** [comment]
I'm using the same Chrome versions right now and the site works fine for me

**Comment by CHEF-KOCH** [comment]
After today's update of Chromium it works now - Or it was fixed by GitHub (because I reported it). Can't say which caused this .... 

Tried all mentioned stuff but none of this worked, then I accidentally connected to the page, and viola it works now. Strange anyway because ping worked, nslookup worked. 

Thanks anyway I close then and hope this never happens again.
