### ISSUE TITLE
Issues with OpenGApps when CMSetupWizard present from CM/LineageOS

### ISSUE THREAD

**Issue by kronflux** [opengapps/opengapps#441]
I do realize there are other issues present in the past regarding CMSetupWizard, however as LineageOS is one of the most popular roms for the majority of current devices, I believe it requires deeper attention.
OpenGApps is essentially the standard for GApps packages now, and it's very unfortunate to not have it work for what is also essentially the standard for custom flashed Roms.

I will also note that this issue has not been specifically noted in the Wiki article related to CMSetupWizard nor do I see any open tickets for the issue at the moment.

Thanks!

**Issue description:**

During initial setup the user is asked to transfer data from another device, however there is no way to skip, and you end up in a loop.
This is only an issues with OpenGApps, and is not present in various other GApps packages including(but not limited to) BaNkS Dynamic GApps.

**Reproduction Steps:**

1.  Clean install LineageOS
2.  Clean install OpenGApps
3.  Run through setup process

**Expected behavior:**

When you hit skip, setup should continue.

As noted, this is only with OpenGApps so one assumes(without the technical knowledge to investigate this further) it is a problem with the end resultant structure/configuration after flashing OpenGApps.

**Workarounds:**

1.  Remove CMSetupWizard, which causes other unexpected behaviors, but does solve this particular issue.
2.  Click skip and back repeatedly until either the app crashes(and setup simply continues) or you manage to skip all the way to the home screen where you can then set up manually from the settings menu.
3.  Flash your rom and complete setup before flashing OpenGApps, then reboot and flash it
4.  Actually perform a device data transfer from an old android device

**Comment by marcthe12** [comment]
same here. If do get pass the cm wizrd somehow. Google playservices crash espicaly when you need to sign in. this could mean work around 2 is proven not to work on moto g2. I will try 3 although that goes my g camara.

**Comment by josephcsible** [comment]
The latest versions of OpenGApps remove CMSetupWizard from CM14+ for this very reason, and the wiki page about issues from removing it only applies to CM13 and below. Given that, what exactly is the problem?

**Comment by marcthe12** [comment]
Play service is faulty. It crashes with google sign in. Lineage os Feb 1 weekly and 3/4 daily open gapps have massive issues  with inital setup (something simple as setup wizard or google sign in dont work). I think Lineage side bug has been fixed but the gapps side on does not work with a down grade of lineage. The current work around is downgrade version of both zips before 1st of feburary

**Comment by josephcsible** [comment]
I still don't get what you're saying. Are you having bugs on LineageOS 13 or 14.1, and did you let it remove CMSetupWizard or force it to keep it? Are you on the latest available builds of both LineageOS and OpenGApps? Also, downgrading anything without doing a full wipe is in general not supported.

**Comment by marcthe12** [comment]
Here is my config
Also here is the details

-  Did a clean installation of LineageOS 14.
- Clean/Dirty flash opengapps
-  Attempt to sign in in google
-  Play service crashes

This occurs to opengapps nightly on 3rd and 4 feb 2017
This is independent to the bug in LineageOS setup wizard nightly 1st feb since I faced the issue on the previous nightly.

The workaround:
Currently 31 Jan nightly works

The device is Moto G2 titan

**Comment by mfonville** [comment]
The CMSetupwizard should have been resolved already, as noted by @josephcsible it is already being removed by default on CM14+

@marcthe12 there were some issues with feb 3 and feb 4 build with the larger packages, because webview was replaced with a version of Chrome that could not provide a webviewprovider. Could you please retry with recent builds to check if your crashing play services has been resolved?

**Comment by marcthe12** [comment]
Right now I can not do a full clean flash. Dirty flash is alright. The addon.d script is faulty though. It causes the Lineage installer to crash with error code 7. the error is roughly at line 142 (where the size of gapps is calculated in order to backup the gapps.)

**Comment by mfonville** [comment]
@marcthe12 could you upload the script file that is currently in your addon.d? That would help to track down that error

**Comment by marcthe12** [comment]
@mfonville [here](https://gist.github.com/marcthe12/b19770ba29b1e130b6e98d0e925f93d2)

**Comment by mfonville** [comment]
@marcthe12 thanks, found that ToyBox doesn't have `tr` in its older builds, thus we have to work around that; should be fixed with https://github.com/opengapps/opengapps/commit/07ce17b6e634afb4dd384226f72e83667f6a66fc

**Comment by marcthe12** [comment]
well It did not work, sumbiting a pull request

**Comment by marcthe12** [comment]
My part of the issue is resolved.

**Comment by mfonville** [comment]
@marcthe12 so no crashing play services anymore?

**Comment by marcthe12** [comment]
nope
