### ISSUE TITLE
Trusted Face not working in Android Oreo 8.0 (arm)

### ISSUE THREAD

**Issue by akshay2shah** [opengapps/opengapps#555]
**I m trying to set Trusted Face in Xperia z2 (sirius) Android Oreo 8.0 (arm) on carbon rom cr6.
Trusted face crash every time i  try to set face.**
i m using Opengapps arm 8.0 mini version.

seems like 64 bit (libfacenet.so) used instead of 32 bit.

_LOG_

11-02 18:43:03.118 I/ActivityManager(692): Killing 4878:com.google.android.gm.exchange/u0a82 (adj 906): empty #17
11-02 18:43:03.120 I/ActivityManager(692): Killing 4917:com.google.android.onetimeinitializer/u0a70 (adj 906): empty #17
11-02 18:43:03.296 I/ActivityManager(692): START u0 {flg=0x2000000 cmp=com.android.facelock/.SetupEnrollmentScreen (has extras)} from uid 10077
11-02 18:43:03.319 I/libcamera(414): HAL_getCameraInfo: E cameraId=0
11-02 18:43:03.320 I/libcamera(414): HAL_getCameraInfo: X
11-02 18:43:03.321 I/libcamera(414): HAL_getCameraInfo: E cameraId=1
11-02 18:43:03.321 I/libcamera(414): HAL_getCameraInfo: X
11-02 18:43:03.360 I/logd.auditd(235): type=1400 audit(0.0:2354): avc: denied { nlmsg_write } for scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=netlink_audit_socket permissive=1
11-02 18:43:03.360 I/logd.auditd(235): type=1400 audit(0.0:2355): avc: denied { audit_control } for capability=30 scontext=u:r:init:s0 tcontext=u:r:init:s0 tclass=capability permissive=1
11-02 18:43:03.363 W/auditd  (235): type=2 
11-02 18:43:03.365 D/AndroidRuntime(5742): Shutting down VM
11-02 18:43:03.365 E/AndroidRuntime(5742): FATAL EXCEPTION: main
11-02 18:43:03.365 E/AndroidRuntime(5742): Process: com.android.facelock, PID: 5742
**11-02 18:43:03.365 E/AndroidRuntime(5742): java.lang.UnsatisfiedLinkError: dlopen failed: "/system/lib/libfacenet.so" is 64-bit instead of 32-bit**
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at java.lang.System.loadLibrary(System.java:1657)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at com.google.android.libraries.vision.facenet.FaceNet.<clinit>(FaceNet.java:67)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at com.google.android.libraries.vision.facenet.FaceNet.createFromAssets(FaceNet.java:118)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at com.android.facelock.FaceLockUtil.initialize(FaceLockUtil.java:148)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at com.android.facelock.SetupEnrollmentScreen.onCreate(SetupEnrollmentScreen.java:517)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.app.Activity.performCreate(Activity.java:7020)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.os.Handler.dispatchMessage(Handler.java:105)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.os.Looper.loop(Looper.java:164)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at android.app.ActivityThread.main(ActivityThread.java:6541)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at java.lang.reflect.Method.invoke(Native Method)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
11-02 18:43:03.365 E/AndroidRuntime(5742): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
11-02 18:43:03.368 W/ActivityManager(692):   Force finishing activity com.android.facelock/.SetupEnrollmentScreen
11-02 18:43:03.370 I/ActivityManager(692): Showing crash dialog for package com.android.facelock u0
11-02 18:43:03.416 I/Adreno-EGL(692): <qeglDrvAPI_eglInitialize:379>: EGL 1.4 QUALCOMM build: Nondeterministic_AU_msm8974_LA.BF.1.1.3_RB1__release_AU (I741a3d36ca)

**Comment by stanis64** [comment]
I have same problem on my Nexus 6 using nano package. Can someone fix it, please?

**Comment by rcstar6696** [comment]
i have the same problem with excat the same error on z2 tablet

**Comment by EpicKip** [comment]
Same problem on my N6 with OpenGapps (2017-11-19). Checked the log and have the same error as you ("/system/lib/libfacenet.so" is 64-bit instead of 32-bit)

**Comment by EpicKip** [comment]
This issue should be posted @ the XDA thread as this is is only for bugs for the installer (just read that)

**Comment by KireKochovski** [comment]
I have the same issue with any arm package.

**Comment by EpicKip** [comment]
Cause they don't seem to care, if they did they would've at least told us something, even that it can't be done would be fine with me. Just anything... But no response, also not on the XDA thread, no response for OP nor for me.

**Comment by teapack** [comment]
I honestly doubt it will ever be resolved. All devices nowadays are 64 bit, and not a single 32 bit device will officially receive Oreo. Therefore Google has no need to make the library for 32 bit devices. And I can imagine that face recognition software/library is way too complicated for us to expect it could ever be ported from the 64 bit version or from 32 bit Nougat one. I guess that's it for 32 bit devices.

**Comment by EpicKip** [comment]
That would mean a response is possible, and also I kind of doubt face unlock changed. (let alone the lib) If the Oreo build changed a lot maybe the lib would be different but idk. But whatever, I consider this feature dead from now

**Comment by teapack** [comment]
Well, I copied the trusted face apk and the libfacenet.so (32 bit) library from my 7.1 system. Then I first tried just placing the library to correct directory in 8.0 (and setting usual privileges via chmod), and it didn't work. I also tried replacing the 8.0 face unlock app with the 7.1 one, but it also didn't work. So I guess something has changed.

Is source code for the library actually available somewhere? If the OpenGapps team gets the library just by extracting it from devices which have it preinstalled, then I'm fairly certain we're out of luck. If there is a source code available and the OpenGapps team compiles it, then someone can have a look at it, see what's changed and port it over to 8.0. I'd gladly look into it, but I haven't found the source code anywhere. And libraries can't be decompiled as e.g. apps can be, so the actual compiled library doesn't help much.

**Comment by EpicKip** [comment]
In that case we are likely out of luck, but still they could'v let us know something...

**Comment by AndrewFatuev** [comment]
I have the same issue with today's ARM 8.0 stock on Nexus 6

**Comment by nalexcastaneda** [comment]
I have the same error with OpenGapps Stock Package in AOSP Extended ROM 5.0 Alpha for Moto G3 Osprey.
Trusted Face Stops in the Smart Lock setup.
I hope you solve it ASAP.
Regards,
Nestor Alexander

**Comment by srinu259** [comment]
I have the same issue on my oneplus one, after reading this thread, I understand I have to live without trusted face or upgrade my phone. For now I will just live with it, thanks for putting this!

**Comment by Subinsmani** [comment]
[Facelock.zip](https://github.com/opengapps/opengapps/files/1618811/Facelock.zip)
Those who have issue with facelock on oreo rom, flash this one after install Gapps.. Becasue i didnt add apk file, only required lib file is there....

**Comment by markbillett** [comment]
Thank you! I will install Oreo and report back.

**Comment by EpicKip** [comment]
@Subinsmani  Where did you get it?

**Comment by Subinsmani** [comment]
@EpicKip Use the zip man till Opengapps Fix the issue. M using this same in 8.1 Oreo, Working perfectly.

**Comment by EpicKip** [comment]
@Subinsmani I asked where you got it from, not if it works. I'm a little skeptical when it comes to unknown zips :)

**Comment by lnx01** [comment]
@EpicKip  If I understand what @Subinsmani is saying, it was extracted directly from the Oreo/8.1 32bit Gapps

**Comment by KKire** [comment]
[Facelock-all.zip](https://github.com/opengapps/opengapps/files/1618900/Facelock-all.zip)
I modified the script to work on all devices becuse it was failing on my OnePlus X.
Thanks man, running on 8.1

**Comment by EpicKip** [comment]
@lnx01 What 8.1 gapps from where? Opengapps does not have facelock lib in the 32 bit gapps yet as google did not make it yet. Thus I'm skeptical and want to know its origin :)

**Comment by KKire** [comment]
There are a lot of unofficial opengapps for 8.1 on xda

**Comment by Subinsmani** [comment]
@EpicKip No source, We did some changes on nougat Facelock Libs... U will not able to find any same zip file or solution anywhere. because this is the first file upload.

**Comment by EpicKip** [comment]
@KKire Those don't have the facelock lib... 

@Subinsmani  Alright, that's what I wanted to know, thanks for the info

**Comment by Subinsmani** [comment]
So enjoy the Facelock, till opengapps got 32bit libs.

**Comment by hakkikaancaliskan** [comment]
Working well thanks.

**Comment by srinu259** [comment]
thanks a ton @KKire and @Subinsmani 
It works on my oneplus one! My phone will now live another year!

**Comment by akshay2shah** [comment]
Thanks @subinsmani 
Tested on xperia Z2 oreo 8.0/8.1. works perfectly.

**Comment by Robinlu1000** [comment]
good job, it works on Nexus6 at 8.1

**Comment by nezorflame** [comment]
@Subinsmani what changes exactly did you make?
If you're able to make a pull request, I'll be happy to approve it and include into my 8.1 builds.

**Comment by Subinsmani** [comment]
I don't think it will add in official open gapps build...

**Comment by nezorflame** [comment]
@Subinsmani I was speaking about my 8.1 builds which can be found here: https://builds.nezorfla.me/opengapps/

**Comment by bmazak** [comment]
Hey guys, I want to thank you Sbinsmani for the Facelock.zip.  It worked like a charm on my OnePlus One with ASOP AEX 15.1 Oreo 8.1.  What exactly was fixed?  Here's the link.  https://github.com/opengapps/opengapps/files/1618900/Facelock-all.zip

**Comment by SpasilliumNexus** [comment]
If anyone with an arm device could, test my nano Gapps packages, and see if Face Unlock works? Android 8.0 or 8.1 required, along with them being installed on a clean ROM.

Once someone verifies that Face Unlock works, I'll submit a pull request.

https://forum.xda-developers.com/showthread.php?t=3743495&p=75648443

**Comment by GNOME-IS-LIFE** [comment]
doesn't work :/ I still have to install the apk for face unlock to appear, and it still crashes :cry:

**Comment by GNOME-IS-LIFE** [comment]
OH this is for arm 32! my phone is an arm64, yet it still doesn't work :(

**Comment by EpicKip** [comment]
@GNOME-IS-LIFE  ...64 bit is supported out of the box -_-

**Comment by FedoraMaster420** [comment]
Thank you for the fix @KKire , however for some reason I can't use Magisk and this fix together on my Galaxy S5 (G900S). After I flash the fix and then Magisk and reboot, the device stays on the normal bootloader (Samsung Galaxy S5 etc) screen, but then goes into download/Odin mode (with the Android logo) and I can't boot into normal Android. The only fix I have found is to either uninstall Magisk or not install the fix, but that isn't the best option as I would much prefer to be rooted with Magisk and have the fix at the same time.

**Comment by CougiTamya** [comment]
@srinu259 , Which ROM and version of GAPPS are you using? I tired flashing @KKire 's file and nothing. So I installed the apk of the Trusted Faces and now it shows up in the Smart Lock section but it crashes as soon as I try to set it up. 

I am on the lineage-15.1-20180430-jgcaap-bacon ROM with micro Open GAPPS 8.1

Any insights would be helpful, I too would like to use my Oneplus One for longer. 

Thank you

**Comment by alexceltare2** [comment]
Does anyone knows what happened with all Trusted Face flashable zips(http://repository.mariobalanica.ml/kqrqkbzumsydw.html?dir=android_development/gapps/trustedface_flashable_zips)?

**Comment by bmazak** [comment]
You see it depends on your Rom.  All these comments and not many indicate what rom they are on.  Above is my link to facelock.zip but it works on The AEX 5.7 Rom 8.1.  I dn't know about other Roms. I did not use an APK.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
