### ISSUE TITLE
new GMS minapi breaks android auto on oreo

### ISSUE THREAD

**Issue by r3t3ch** [opengapps/opengapps#707]
Test case uses any device running lineage-15.1 with any opengapps build newer than 20180910.

After commit dda2a5b, a newer gms is installed on android 8.1.0 devices. It selects the [min API 27 variant](https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-14-7-99-release/google-play-services-14-7-99-110400-223214910-android-apk-download/) rather than the [min API 26 variant](https://www.apkmirror.com/apk/google-inc/google-play-services/google-play-services-14-7-99-release/google-play-services-14-7-99-090400-223214910-android-apk-download/).

For whatever reason (why are gms builds targeting Android 8.1+ even a thing?), this breaks android auto, resulting in the error message "Something went wrong. Google Play services doesn't seem to be working right now." upon launching the app.

This is more than likely an opengapps issue rather than a lineage issue since the play store's manual update behavior also opts for the API 26 variant.

This issue has also been reported several times elsewhere over the past few months (e.g. [1](https://reddit.com/r/LineageOS/comments/9qris6/mi_mix_2_and_android_auto/), [2](https://reddit.com/r/LineageOS/comments/9rh75h/android_auto_does_not_start_google_play_service/), [3](https://forum.xda-developers.com/android/help/qa-gapps-android-5-1-5-0-4-4-t3124506/post77966929#post77966929)).

**Comment by viggy96** [comment]
I've experienced this as well, with the stock package. I've managed to capture a logcat of the crash of Android Auto:
```
12-30 16:15:36.398  7210  7210 E AndroidRuntime: FATAL EXCEPTION: main
12-30 16:15:36.398  7210  7210 E AndroidRuntime: Process: com.google.android.projection.gearhead:projection, PID: 7210
12-30 16:15:36.398  7210  7210 E AndroidRuntime: java.lang.IllegalStateException: Failed to connect to car service: API_UNAVAILABLE
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at apf.a(SourceFile:120)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at eva.c(SourceFile:15)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at bid.b(SourceFile:405)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at bid.a(SourceFile:434)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at big.a(SourceFile:31)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at cmu.a(SourceFile:9)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiClientImpl.g(SourceFile:328)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiClientConnecting.i(SourceFile:154)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiClientConnecting.St(SourceFile:62)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.common.api.internal.GoogleApiClientConnecting$a.j(SourceFile:27)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$PostServiceBindingCallback.o(SourceFile:5)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$a.aY(SourceFile:29)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.common.internal.BaseGmsClient$b.handleMessage(SourceFile:78)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.google.android.gms.libs.punchclock.threads.TracingHandler.dispatchMessage(SourceFile:9)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:164)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6494)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:440)
12-30 16:15:36.398  7210  7210 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by viggy96** [comment]
This Android Auto issue appears to be fixed in the 10 January 2019 build of OpenGApps.

**Comment by swiezak** [comment]
According to several reports it might have something to do with initial config of AA. When it is done AA seems to be working well even with newest opengapps

**Comment by viggy96** [comment]
@swiezak I completed a new install of Android Auto with the 10 January build of OpenGApps. I went through the initial setup screens with it, without fault. The problem seems to have been fixed. Try flashing the latest OpenGApps, and your problem should be solved.

**Comment by swiezak** [comment]
For me this didn't work. though I am using arm(v7) (not arm64) arch. Used open_gapps-arm-8.1-mini-20190110 and android auto 3.8.584563-release. Might be I need to wait for 3.9.5850 to release v7 as well.
Would be nice to check what changed between 3.8 and 3.9

**Comment by swiezak** [comment]
The issue is still present.
Config open_gapps-arm-8.1-mini-20190117, ROM lineage-15.1-20180116-UNOFFICIAL-virgo phone xiaomi note(virgo) arm-v7 arch.
Reinstalled the whole system from scratch and issue exists. Starting to think might be something else going on.

**Comment by andre95d** [comment]
I can confirm this problem for open_gapps-arm64-8.1-aroma-20190418 too. I installed this over an exiting pico installation. I will keep AA in /data for now.

**Comment by osm0sis** [comment]
Purging issues. Feel free to request reopening if it is still reproducible on the latest build.
